services:

  api:
    build: .
    container_name: cyberface-rag
    ports:
      - "8000:8000"
    volumes:
      - ./chromaDB/:/app/chromaDB/
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
